In [1]:
import pandas as pd 
import numpy as np

In [2]:
train_df=pd.read_csv('data/train_imp.csv')

In [3]:
test_df=pd.read_csv('data/test_imp.csv')

In [4]:
all_df=pd.concat([train_df,test_df])

In [5]:
df_non_num = all_df.select_dtypes(exclude=[np.number])
df_non_num

      product_code attribute_0 attribute_1
0                A  material_7  material_8
1                A  material_7  material_8
2                A  material_7  material_8
3                A  material_7  material_8
4                A  material_7  material_8
...            ...         ...         ...
20770            I  material_7  material_5
20771            I  material_7  material_5
20772            I  material_7  material_5
20773            I  material_7  material_5
20774            I  material_7  material_5

[47345 rows x 3 columns]

In [6]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
enc.fit(df_non_num)
df_non_num_new=enc.transform(df_non_num)

In [7]:
df_non_num_new=pd.DataFrame(df_non_num_new,columns=df_non_num.columns)
df_non_num_new

       product_code  attribute_0  attribute_1
0               0.0          1.0          3.0
1               0.0          1.0          3.0
2               0.0          1.0          3.0
3               0.0          1.0          3.0
4               0.0          1.0          3.0
...             ...          ...          ...
47340           8.0          1.0          0.0
47341           8.0          1.0          0.0
47342           8.0          1.0          0.0
47343           8.0          1.0          0.0
47344           8.0          1.0          0.0

[47345 rows x 3 columns]

In [8]:
all_df[df_non_num.columns]=df_non_num_new
all_df

,id,loading,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,...,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,product_code,attribute_0,attribute_1,failure
0,0,80.10,9.0,5.0,7.0,8.0,4.0,18.040,12.518000,15.748,...,15.193,15.029,13.638146,13.034,14.684000,764.100,0.0,1.0,3.0,0.0
1,1,84.89,9.0,5.0,14.0,3.0,3.0,18.213,11.540000,17.717,...,11.755,14.732,15.425000,14.395,15.631000,682.057,0.0,1.0,3.0,0.0
2,2,82.43,9.0,5.0,12.0,1.0,5.0,18.057,11.652000,16.738,...,13.798,16.711,18.631000,14.094,17.946000,663.376,0.0,1.0,3.0,0.0
3,3,101.07,9.0,5.0,13.0,2.0,6.0,17.295,11.188000,18.576,...,10.020,15.250,15.562000,16.154,17.172000,826.282,0.0,1.0,3.0,0.0
4,4,188.06,9.0,5.0,9.0,2.0,8.0,19.346,12.950000,16.990,...,12.428,16.182,12.760000,13.153,16.412000,579.885,0.0,1.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20770,47340,144.74,9.0,5.0,0.0,4.0,9.0,18.465,12.570000,18.146,...,11.562,17.246,15.131000,15.209,14.010752,696.466,3.0,1.0,0.0,NaN
20771,47341,74.53,9.0,5.0,4.0,8.0,7.0,18.900,9.896000,18.288,...,13.564,15.494,15.296000,13.812,16.501000,613.249,3.0,1.0,0.0,NaN
20772,47342,67.73,9.0,5.0,10.0,11.0,2.0,18.656,10.033195,18.242,...,11.134,16.519,15.525000,14.175,17.728000,783.349,3.0,1.0,0.0,NaN
20773,47343,126.15,9.0,5.0,8.0,16.0,11.0,16.536,11.226000,18.144,...,9.319,15.817,17.403000,16.437,15.179000,745.210,3.0,1.0,0.0,NaN
20774,47344,85.97,9.0,5.0,0.0,11.0,11.0,18.373,11.210000,17.030,...,13.726,14.605,17.460000,16.261,16.482000,647.980,3.0,1.0,0.0,NaN

In [9]:
all_df=all_df.iloc[:,1:]

In [10]:
train_df=all_df[~all_df['failure'].isnull()]
train_df

,loading,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,measurement_6,...,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,product_code,attribute_0,attribute_1,failure
0,80.10,9.0,5.0,7.0,8.0,4.0,18.040,12.518000,15.748,19.292,...,15.193,15.029,13.638146,13.034,14.684000,764.100,0.0,1.0,3.0,0.0
1,84.89,9.0,5.0,14.0,3.0,3.0,18.213,11.540000,17.717,17.893,...,11.755,14.732,15.425000,14.395,15.631000,682.057,0.0,1.0,3.0,0.0
2,82.43,9.0,5.0,12.0,1.0,5.0,18.057,11.652000,16.738,18.240,...,13.798,16.711,18.631000,14.094,17.946000,663.376,0.0,1.0,3.0,0.0
3,101.07,9.0,5.0,13.0,2.0,6.0,17.295,11.188000,18.576,18.339,...,10.020,15.250,15.562000,16.154,17.172000,826.282,0.0,1.0,3.0,0.0
4,188.06,9.0,5.0,9.0,2.0,8.0,19.346,12.950000,16.990,15.746,...,12.428,16.182,12.760000,13.153,16.412000,579.885,0.0,1.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26565,158.95,6.0,9.0,6.0,16.0,4.0,16.301,13.259000,18.068,15.505,...,10.112,15.795,18.572000,16.144,13.279117,729.131,4.0,1.0,1.0,0.0
26566,146.02,6.0,9.0,10.0,12.0,8.0,17.543,10.036905,17.984,19.078,...,10.234,14.450,14.322000,13.146,16.471000,853.924,4.0,1.0,1.0,0.0
26567,115.62,6.0,9.0,1.0,10.0,1.0,15.670,11.535000,16.778,18.385,...,8.668,15.069,16.599000,15.590,14.065000,750.364,4.0,1.0,1.0,0.0
26568,106.38,6.0,9.0,2.0,9.0,4.0,18.059,10.031023,16.918,18.101,...,14.928,16.273,15.485000,13.624,12.865000,730.156,4.0,1.0,1.0,0.0
26569,131.20,6.0,9.0,6.0,19.0,1.0,18.034,11.431000,16.918,17.129,...,11.006,15.875,13.366000,16.527,17.890000,602.354,4.0,1.0,1.0,0.0

In [11]:
test_df=all_df[all_df['failure'].isnull()]
test_df

,loading,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,measurement_6,...,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,product_code,attribute_0,attribute_1,failure
0,119.57,6.0,4.0,6.0,9.0,6.0,19.305,10.178000,17.534,18.168000,...,13.772,13.659,16.825,13.742,17.710000,634.612,0.0,1.0,3.0,NaN
1,113.51,6.0,4.0,11.0,8.0,0.0,17.883,11.927000,17.228,16.033000,...,12.473,17.468,16.708,14.776,14.102000,537.037,0.0,1.0,3.0,NaN
2,112.16,6.0,4.0,8.0,12.0,4.0,18.475,10.481000,16.619,18.189000,...,10.907,13.363,15.737,17.065,16.021000,658.995,0.0,1.0,3.0,NaN
3,112.72,6.0,4.0,8.0,11.0,10.0,16.518,10.888000,15.293,18.592000,...,10.933,15.501,15.667,12.620,16.111000,594.301,0.0,1.0,3.0,NaN
4,208.00,6.0,4.0,14.0,16.0,8.0,17.808,12.693000,17.678,15.814000,...,11.941,16.070,16.183,13.324,17.150000,801.044,0.0,1.0,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20770,144.74,9.0,5.0,0.0,4.0,9.0,18.465,12.570000,18.146,17.089000,...,11.562,17.246,15.131,15.209,14.010752,696.466,3.0,1.0,0.0,NaN
20771,74.53,9.0,5.0,4.0,8.0,7.0,18.900,9.896000,18.288,14.592782,...,13.564,15.494,15.296,13.812,16.501000,613.249,3.0,1.0,0.0,NaN
20772,67.73,9.0,5.0,10.0,11.0,2.0,18.656,10.033195,18.242,17.910000,...,11.134,16.519,15.525,14.175,17.728000,783.349,3.0,1.0,0.0,NaN
20773,126.15,9.0,5.0,8.0,16.0,11.0,16.536,11.226000,18.144,17.250000,...,9.319,15.817,17.403,16.437,15.179000,745.210,3.0,1.0,0.0,NaN
20774,85.97,9.0,5.0,0.0,11.0,11.0,18.373,11.210000,17.030,18.406000,...,13.726,14.605,17.460,16.261,16.482000,647.980,3.0,1.0,0.0,NaN

In [12]:
train_X=train_df.iloc[:,:-1]
train_y=train_df.iloc[:,-1]

In [13]:
from xgboost import XGBClassifier

# 建立 XGBClassifier 模型
xgboostModel = XGBClassifier(
        eval_metric="logloss",
        max_depth=11,
        learning_rate=0.0642,
        n_estimators=800,
        min_child_weight=7,
        grow_policy="depthwise",
        gamma=1.2840e-06)
# 使用訓練資料訓練模型
xgboostModel.fit(train_X, train_y)
# 使用訓練資料預測分類

C:\Users\highs\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              eval_metric='logloss', gamma=1.284e-06, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.0642,
              max_delta_step=0, max_depth=11, min_child_weight=7, missing=nan,
              monotone_constraints='()', n_estimators=800, n_jobs=6,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [14]:
predicted = xgboostModel.predict(train_X)

In [15]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(train_y, predicted)
accuracy

0.9978547233722244

In [16]:
train_X

,loading,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,measurement_6,...,measurement_11,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,product_code,attribute_0,attribute_1
0,80.10,9.0,5.0,7.0,8.0,4.0,18.040,12.518000,15.748,19.292,...,17.59400,15.193,15.029,13.638146,13.034,14.684000,764.100,0.0,1.0,3.0
1,84.89,9.0,5.0,14.0,3.0,3.0,18.213,11.540000,17.717,17.893,...,17.91500,11.755,14.732,15.425000,14.395,15.631000,682.057,0.0,1.0,3.0
2,82.43,9.0,5.0,12.0,1.0,5.0,18.057,11.652000,16.738,18.240,...,15.93469,13.798,16.711,18.631000,14.094,17.946000,663.376,0.0,1.0,3.0
3,101.07,9.0,5.0,13.0,2.0,6.0,17.295,11.188000,18.576,18.339,...,18.37700,10.020,15.250,15.562000,16.154,17.172000,826.282,0.0,1.0,3.0
4,188.06,9.0,5.0,9.0,2.0,8.0,19.346,12.950000,16.990,15.746,...,19.93200,12.428,16.182,12.760000,13.153,16.412000,579.885,0.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26565,158.95,6.0,9.0,6.0,16.0,4.0,16.301,13.259000,18.068,15.505,...,17.94200,10.112,15.795,18.572000,16.144,13.279117,729.131,4.0,1.0,1.0
26566,146.02,6.0,9.0,10.0,12.0,8.0,17.543,10.036905,17.984,19.078,...,20.56400,10.234,14.450,14.322000,13.146,16.471000,853.924,4.0,1.0,1.0
26567,115.62,6.0,9.0,1.0,10.0,1.0,15.670,11.535000,16.778,18.385,...,17.47600,8.668,15.069,16.599000,15.590,14.065000,750.364,4.0,1.0,1.0
26568,106.38,6.0,9.0,2.0,9.0,4.0,18.059,10.031023,16.918,18.101,...,17.81400,14.928,16.273,15.485000,13.624,12.865000,730.156,4.0,1.0,1.0
26569,131.20,6.0,9.0,6.0,19.0,1.0,18.034,11.431000,16.918,17.129,...,19.70300,11.006,15.875,13.366000,16.527,17.890000,602.354,4.0,1.0,1.0

In [17]:
test_df

,loading,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,measurement_6,...,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,product_code,attribute_0,attribute_1,failure
0,119.57,6.0,4.0,6.0,9.0,6.0,19.305,10.178000,17.534,18.168000,...,13.772,13.659,16.825,13.742,17.710000,634.612,0.0,1.0,3.0,NaN
1,113.51,6.0,4.0,11.0,8.0,0.0,17.883,11.927000,17.228,16.033000,...,12.473,17.468,16.708,14.776,14.102000,537.037,0.0,1.0,3.0,NaN
2,112.16,6.0,4.0,8.0,12.0,4.0,18.475,10.481000,16.619,18.189000,...,10.907,13.363,15.737,17.065,16.021000,658.995,0.0,1.0,3.0,NaN
3,112.72,6.0,4.0,8.0,11.0,10.0,16.518,10.888000,15.293,18.592000,...,10.933,15.501,15.667,12.620,16.111000,594.301,0.0,1.0,3.0,NaN
4,208.00,6.0,4.0,14.0,16.0,8.0,17.808,12.693000,17.678,15.814000,...,11.941,16.070,16.183,13.324,17.150000,801.044,0.0,1.0,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20770,144.74,9.0,5.0,0.0,4.0,9.0,18.465,12.570000,18.146,17.089000,...,11.562,17.246,15.131,15.209,14.010752,696.466,3.0,1.0,0.0,NaN
20771,74.53,9.0,5.0,4.0,8.0,7.0,18.900,9.896000,18.288,14.592782,...,13.564,15.494,15.296,13.812,16.501000,613.249,3.0,1.0,0.0,NaN
20772,67.73,9.0,5.0,10.0,11.0,2.0,18.656,10.033195,18.242,17.910000,...,11.134,16.519,15.525,14.175,17.728000,783.349,3.0,1.0,0.0,NaN
20773,126.15,9.0,5.0,8.0,16.0,11.0,16.536,11.226000,18.144,17.250000,...,9.319,15.817,17.403,16.437,15.179000,745.210,3.0,1.0,0.0,NaN
20774,85.97,9.0,5.0,0.0,11.0,11.0,18.373,11.210000,17.030,18.406000,...,13.726,14.605,17.460,16.261,16.482000,647.980,3.0,1.0,0.0,NaN

In [18]:
train_X

,loading,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,measurement_6,...,measurement_11,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,product_code,attribute_0,attribute_1
0,80.10,9.0,5.0,7.0,8.0,4.0,18.040,12.518000,15.748,19.292,...,17.59400,15.193,15.029,13.638146,13.034,14.684000,764.100,0.0,1.0,3.0
1,84.89,9.0,5.0,14.0,3.0,3.0,18.213,11.540000,17.717,17.893,...,17.91500,11.755,14.732,15.425000,14.395,15.631000,682.057,0.0,1.0,3.0
2,82.43,9.0,5.0,12.0,1.0,5.0,18.057,11.652000,16.738,18.240,...,15.93469,13.798,16.711,18.631000,14.094,17.946000,663.376,0.0,1.0,3.0
3,101.07,9.0,5.0,13.0,2.0,6.0,17.295,11.188000,18.576,18.339,...,18.37700,10.020,15.250,15.562000,16.154,17.172000,826.282,0.0,1.0,3.0
4,188.06,9.0,5.0,9.0,2.0,8.0,19.346,12.950000,16.990,15.746,...,19.93200,12.428,16.182,12.760000,13.153,16.412000,579.885,0.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26565,158.95,6.0,9.0,6.0,16.0,4.0,16.301,13.259000,18.068,15.505,...,17.94200,10.112,15.795,18.572000,16.144,13.279117,729.131,4.0,1.0,1.0
26566,146.02,6.0,9.0,10.0,12.0,8.0,17.543,10.036905,17.984,19.078,...,20.56400,10.234,14.450,14.322000,13.146,16.471000,853.924,4.0,1.0,1.0
26567,115.62,6.0,9.0,1.0,10.0,1.0,15.670,11.535000,16.778,18.385,...,17.47600,8.668,15.069,16.599000,15.590,14.065000,750.364,4.0,1.0,1.0
26568,106.38,6.0,9.0,2.0,9.0,4.0,18.059,10.031023,16.918,18.101,...,17.81400,14.928,16.273,15.485000,13.624,12.865000,730.156,4.0,1.0,1.0
26569,131.20,6.0,9.0,6.0,19.0,1.0,18.034,11.431000,16.918,17.129,...,19.70300,11.006,15.875,13.366000,16.527,17.890000,602.354,4.0,1.0,1.0

In [19]:
pred_prob=xgboostModel.predict_proba(test_df.iloc[:,:-1])
pred_prob

array([[0.754891  , 0.24510904],
       [0.9257173 , 0.07428271],
       [0.8454547 , 0.15454528],
       ...,
       [0.9369543 , 0.0630457 ],
       [0.77936137, 0.2206386 ],
       [0.9528037 , 0.04719634]], dtype=float32)

In [20]:
pred_prob[:,0]

array([0.754891  , 0.9257173 , 0.8454547 , ..., 0.9369543 , 0.77936137,
       0.9528037 ], dtype=float32)

In [21]:
submission = pd.read_csv('data/sample_submission.csv')

In [22]:
%%time
submission['failure'] = pred_prob[:,1]
submission.to_csv('result/baseline.csv', index = False)
submission.head()

Wall time: 41.1 ms

      id   failure
0  26570  0.245109
1  26571  0.074283
2  26572  0.154545
3  26573  0.129557
4  26574  0.274025