In [53]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [23]:
train_df=pd.read_csv('data/train_imp.csv')

In [24]:
test_df=pd.read_csv('data/test_imp.csv')

In [25]:
all_df=pd.concat([train_df,test_df])

In [26]:
train_df

,id,loading,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,...,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,product_code,attribute_0,attribute_1,failure
0,0,80.10,9.0,5.0,7.0,8.0,4.0,18.040,12.518000,15.748,...,15.193,15.029,13.638146,13.034,14.684000,764.100,A,material_7,material_8,0.0
1,1,84.89,9.0,5.0,14.0,3.0,3.0,18.213,11.540000,17.717,...,11.755,14.732,15.425000,14.395,15.631000,682.057,A,material_7,material_8,0.0
2,2,82.43,9.0,5.0,12.0,1.0,5.0,18.057,11.652000,16.738,...,13.798,16.711,18.631000,14.094,17.946000,663.376,A,material_7,material_8,0.0
3,3,101.07,9.0,5.0,13.0,2.0,6.0,17.295,11.188000,18.576,...,10.020,15.250,15.562000,16.154,17.172000,826.282,A,material_7,material_8,0.0
4,4,188.06,9.0,5.0,9.0,2.0,8.0,19.346,12.950000,16.990,...,12.428,16.182,12.760000,13.153,16.412000,579.885,A,material_7,material_8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26565,26565,158.95,6.0,9.0,6.0,16.0,4.0,16.301,13.259000,18.068,...,10.112,15.795,18.572000,16.144,13.279117,729.131,E,material_7,material_6,0.0
26566,26566,146.02,6.0,9.0,10.0,12.0,8.0,17.543,10.036905,17.984,...,10.234,14.450,14.322000,13.146,16.471000,853.924,E,material_7,material_6,0.0
26567,26567,115.62,6.0,9.0,1.0,10.0,1.0,15.670,11.535000,16.778,...,8.668,15.069,16.599000,15.590,14.065000,750.364,E,material_7,material_6,0.0
26568,26568,106.38,6.0,9.0,2.0,9.0,4.0,18.059,10.031023,16.918,...,14.928,16.273,15.485000,13.624,12.865000,730.156,E,material_7,material_6,0.0
26569,26569,131.20,6.0,9.0,6.0,19.0,1.0,18.034,11.431000,16.918,...,11.006,15.875,13.366000,16.527,17.890000,602.354,E,material_7,material_6,0.0

In [27]:
test_df

,id,loading,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,...,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,product_code,attribute_0,attribute_1,failure
0,26570,119.57,6.0,4.0,6.0,9.0,6.0,19.305,10.178000,17.534,...,13.772,13.659,16.825,13.742,17.710000,634.612,F,material_5,material_6,NaN
1,26571,113.51,6.0,4.0,11.0,8.0,0.0,17.883,11.927000,17.228,...,12.473,17.468,16.708,14.776,14.102000,537.037,F,material_5,material_6,NaN
2,26572,112.16,6.0,4.0,8.0,12.0,4.0,18.475,10.481000,16.619,...,10.907,13.363,15.737,17.065,16.021000,658.995,F,material_5,material_6,NaN
3,26573,112.72,6.0,4.0,8.0,11.0,10.0,16.518,10.888000,15.293,...,10.933,15.501,15.667,12.620,16.111000,594.301,F,material_5,material_6,NaN
4,26574,208.00,6.0,4.0,14.0,16.0,8.0,17.808,12.693000,17.678,...,11.941,16.070,16.183,13.324,17.150000,801.044,F,material_5,material_6,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20770,47340,144.74,9.0,5.0,0.0,4.0,9.0,18.465,12.570000,18.146,...,11.562,17.246,15.131,15.209,14.010752,696.466,I,material_7,material_5,NaN
20771,47341,74.53,9.0,5.0,4.0,8.0,7.0,18.900,9.896000,18.288,...,13.564,15.494,15.296,13.812,16.501000,613.249,I,material_7,material_5,NaN
20772,47342,67.73,9.0,5.0,10.0,11.0,2.0,18.656,10.033195,18.242,...,11.134,16.519,15.525,14.175,17.728000,783.349,I,material_7,material_5,NaN
20773,47343,126.15,9.0,5.0,8.0,16.0,11.0,16.536,11.226000,18.144,...,9.319,15.817,17.403,16.437,15.179000,745.210,I,material_7,material_5,NaN
20774,47344,85.97,9.0,5.0,0.0,11.0,11.0,18.373,11.210000,17.030,...,13.726,14.605,17.460,16.261,16.482000,647.980,I,material_7,material_5,NaN

In [28]:
all_df=all_df.drop(['attribute_0','attribute_1','attribute_2','attribute_3'], axis=1)

In [29]:
train_df=all_df[~all_df['failure'].isnull()]
train_df

,id,loading,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,measurement_6,measurement_7,...,measurement_10,measurement_11,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,product_code,failure
0,0,80.10,7.0,8.0,4.0,18.040,12.518000,15.748,19.292,11.739,...,15.859,17.59400,15.193,15.029,13.638146,13.034,14.684000,764.100,A,0.0
1,1,84.89,14.0,3.0,3.0,18.213,11.540000,17.717,17.893,12.748,...,17.947,17.91500,11.755,14.732,15.425000,14.395,15.631000,682.057,A,0.0
2,2,82.43,12.0,1.0,5.0,18.057,11.652000,16.738,18.240,12.718,...,15.607,15.93469,13.798,16.711,18.631000,14.094,17.946000,663.376,A,0.0
3,3,101.07,13.0,2.0,6.0,17.295,11.188000,18.576,18.339,12.583,...,16.346,18.37700,10.020,15.250,15.562000,16.154,17.172000,826.282,A,0.0
4,4,188.06,9.0,2.0,8.0,19.346,12.950000,16.990,15.746,11.306,...,17.082,19.93200,12.428,16.182,12.760000,13.153,16.412000,579.885,A,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26565,26565,158.95,6.0,16.0,4.0,16.301,13.259000,18.068,15.505,10.865,...,12.177,17.94200,10.112,15.795,18.572000,16.144,13.279117,729.131,E,0.0
26566,26566,146.02,10.0,12.0,8.0,17.543,10.036905,17.984,19.078,11.139,...,14.179,20.56400,10.234,14.450,14.322000,13.146,16.471000,853.924,E,0.0
26567,26567,115.62,1.0,10.0,1.0,15.670,11.535000,16.778,18.385,11.630,...,16.437,17.47600,8.668,15.069,16.599000,15.590,14.065000,750.364,E,0.0
26568,26568,106.38,2.0,9.0,4.0,18.059,10.031023,16.918,18.101,11.713,...,17.064,17.81400,14.928,16.273,15.485000,13.624,12.865000,730.156,E,0.0
26569,26569,131.20,6.0,19.0,1.0,18.034,11.431000,16.918,17.129,12.713,...,15.603,19.70300,11.006,15.875,13.366000,16.527,17.890000,602.354,E,0.0

In [30]:
test_df=all_df[all_df['failure'].isnull()]
test_df

,id,loading,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,measurement_6,measurement_7,...,measurement_10,measurement_11,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,product_code,failure
0,26570,119.57,6.0,9.0,6.0,19.305,10.178000,17.534,18.168000,11.598,...,15.909000,18.070000,13.772,13.659,16.825,13.742,17.710000,634.612,F,NaN
1,26571,113.51,11.0,8.0,0.0,17.883,11.927000,17.228,16.033000,11.179,...,13.998000,15.188263,12.473,17.468,16.708,14.776,14.102000,537.037,F,NaN
2,26572,112.16,8.0,12.0,4.0,18.475,10.481000,16.619,18.189000,12.126,...,17.046000,18.086000,10.907,13.363,15.737,17.065,16.021000,658.995,F,NaN
3,26573,112.72,8.0,11.0,10.0,16.518,10.888000,15.293,18.592000,11.304,...,18.165000,16.163000,10.933,15.501,15.667,12.620,16.111000,594.301,F,NaN
4,26574,208.00,14.0,16.0,8.0,17.808,12.693000,17.678,15.814000,13.431,...,14.578000,17.849000,11.941,16.070,16.183,13.324,17.150000,801.044,F,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20770,47340,144.74,0.0,4.0,9.0,18.465,12.570000,18.146,17.089000,11.204,...,13.471153,19.771000,11.562,17.246,15.131,15.209,14.010752,696.466,I,NaN
20771,47341,74.53,4.0,8.0,7.0,18.900,9.896000,18.288,14.592782,11.747,...,16.027000,15.694000,13.564,15.494,15.296,13.812,16.501000,613.249,I,NaN
20772,47342,67.73,10.0,11.0,2.0,18.656,10.033195,18.242,17.910000,12.081,...,16.137000,20.612000,11.134,16.519,15.525,14.175,17.728000,783.349,I,NaN
20773,47343,126.15,8.0,16.0,11.0,16.536,11.226000,18.144,17.250000,12.692,...,15.422000,19.496000,9.319,15.817,17.403,16.437,15.179000,745.210,I,NaN
20774,47344,85.97,0.0,11.0,11.0,18.373,11.210000,17.030,18.406000,10.181,...,17.270000,17.924000,13.726,14.605,17.460,16.261,16.482000,647.980,I,NaN

In [ ]:
ssss

In [31]:
from datetime import datetime
now = datetime.now()
current_time = now.strftime("%Y_%m_%d_%H_%M_%S")
print("Current Time =", current_time)
train_df.to_pickle('feature/'+current_time+'_train.pkl')  
test_df.to_pickle('feature/'+current_time+'_test.pkl')

Current Time = 2022_08_02_02_15_56

In [32]:
ssss

NameError: name 'ssss' is not defined