# Mice 補值

In [28]:
import pandas as pd 
import numpy as np

In [29]:
train_df=pd.read_csv('data/train.csv')

In [30]:
test_df=pd.read_csv('data/test.csv')

In [31]:
all_data=pd.concat([train_df,test_df])

In [32]:
all_data_X=all_data.iloc[:,:-1]

In [33]:
all_data_y=all_data.iloc[:,-1]

In [35]:
# select the numeric columns
df_num = all_data_X.select_dtypes(include=[np.number])
# select non-numeric columns
df_non_num = all_data_X.select_dtypes(exclude=[np.number])

In [36]:
df_num

,id,loading,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,...,measurement_8,measurement_9,measurement_10,measurement_11,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17
0,0,80.10,9,5,7,8,4,18.040,12.518,15.748,...,20.155,10.672,15.859,17.594,15.193,15.029,NaN,13.034,14.684,764.100
1,1,84.89,9,5,14,3,3,18.213,11.540,17.717,...,17.889,12.448,17.947,17.915,11.755,14.732,15.425,14.395,15.631,682.057
2,2,82.43,9,5,12,1,5,18.057,11.652,16.738,...,18.288,12.715,15.607,NaN,13.798,16.711,18.631,14.094,17.946,663.376
3,3,101.07,9,5,13,2,6,17.295,11.188,18.576,...,19.060,12.471,16.346,18.377,10.020,15.250,15.562,16.154,17.172,826.282
4,4,188.06,9,5,9,2,8,19.346,12.950,16.990,...,18.093,10.337,17.082,19.932,12.428,16.182,12.760,13.153,16.412,579.885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20770,47340,144.74,9,5,0,4,9,18.465,12.570,18.146,...,18.573,11.691,NaN,19.771,11.562,17.246,15.131,15.209,NaN,696.466
20771,47341,74.53,9,5,4,8,7,18.900,9.896,18.288,...,17.917,10.980,16.027,15.694,13.564,15.494,15.296,13.812,16.501,613.249
20772,47342,67.73,9,5,10,11,2,18.656,NaN,18.242,...,19.630,10.436,16.137,20.612,11.134,16.519,15.525,14.175,17.728,783.349
20773,47343,126.15,9,5,8,16,11,16.536,11.226,18.144,...,19.575,12.672,15.422,19.496,9.319,15.817,17.403,16.437,15.179,745.210
20774,47344,85.97,9,5,0,11,11,18.373,11.210,17.030,...,19.253,9.977,17.270,17.924,13.726,14.605,17.460,16.261,16.482,647.980

In [37]:
df_num_without_id=df_num.iloc[:,1:]

In [38]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
import xgboost

data=df_num_without_id.copy()

#setting up the imputer

imp = IterativeImputer(
    estimator=xgboost.XGBRegressor(
        n_estimators=5,
        random_state=1,
        tree_method='gpu_hist',
    ),
    missing_values=np.nan,
    max_iter=10,
    initial_strategy='mean',
    imputation_order='ascending',
    verbose=2,
    random_state=1
)

data[:] = imp.fit_transform(data)
data.shape

[IterativeImputer] Completing matrix with shape (47345, 21)
[IterativeImputer] Ending imputation round 1/10, elapsed time 1.87
[IterativeImputer] Change: 362.86725435495225, scaled tolerance: 1.3127939999999998
[IterativeImputer] Ending imputation round 2/10, elapsed time 3.02
[IterativeImputer] Change: 57.77443218231201, scaled tolerance: 1.3127939999999998
[IterativeImputer] Ending imputation round 3/10, elapsed time 4.16
[IterativeImputer] Change: 99.58937549591064, scaled tolerance: 1.3127939999999998
[IterativeImputer] Ending imputation round 4/10, elapsed time 5.32
[IterativeImputer] Change: 94.18572521209717, scaled tolerance: 1.3127939999999998
[IterativeImputer] Ending imputation round 5/10, elapsed time 6.47
[IterativeImputer] Change: 44.77462673187256, scaled tolerance: 1.3127939999999998
[IterativeImputer] Ending imputation round 6/10, elapsed time 7.61
[IterativeImputer] Change: 39.15985107421875, scaled tolerance: 1.3127939999999998
[IterativeImputer] Ending imputation round 7/10, elapsed time 8.76
[IterativeImputer] Change: 99.80363845825195, scaled tolerance: 1.3127939999999998
[IterativeImputer] Ending imputation round 8/10, elapsed time 9.90
[IterativeImputer] Change: 81.32979774475098, scaled tolerance: 1.3127939999999998
[IterativeImputer] Ending imputation round 9/10, elapsed time 11.03
[IterativeImputer] Change: 65.06591987609863, scaled tolerance: 1.3127939999999998
[IterativeImputer] Ending imputation round 10/10, elapsed time 12.17
[IterativeImputer] Change: 120.04824256896973, scaled tolerance: 1.3127939999999998

C:\Users\highs\anaconda3\lib\site-packages\sklearn\impute\_iterative.py:686: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  " reached.", ConvergenceWarning)

(47345, 21)

In [42]:
df_num_imp=pd.concat([df_num.id,data],axis=1)

In [43]:
all_data_X_imp=pd.concat([df_num_imp,df_non_num,all_data_y],axis=1)

In [44]:
all_data_X_imp

,id,loading,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,...,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,product_code,attribute_0,attribute_1,failure
0,0,80.10,9.0,5.0,7.0,8.0,4.0,18.040,12.518000,15.748,...,15.193,15.029,13.638146,13.034,14.684000,764.100,A,material_7,material_8,0.0
1,1,84.89,9.0,5.0,14.0,3.0,3.0,18.213,11.540000,17.717,...,11.755,14.732,15.425000,14.395,15.631000,682.057,A,material_7,material_8,0.0
2,2,82.43,9.0,5.0,12.0,1.0,5.0,18.057,11.652000,16.738,...,13.798,16.711,18.631000,14.094,17.946000,663.376,A,material_7,material_8,0.0
3,3,101.07,9.0,5.0,13.0,2.0,6.0,17.295,11.188000,18.576,...,10.020,15.250,15.562000,16.154,17.172000,826.282,A,material_7,material_8,0.0
4,4,188.06,9.0,5.0,9.0,2.0,8.0,19.346,12.950000,16.990,...,12.428,16.182,12.760000,13.153,16.412000,579.885,A,material_7,material_8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20770,47340,144.74,9.0,5.0,0.0,4.0,9.0,18.465,12.570000,18.146,...,11.562,17.246,15.131000,15.209,14.010752,696.466,I,material_7,material_5,NaN
20771,47341,74.53,9.0,5.0,4.0,8.0,7.0,18.900,9.896000,18.288,...,13.564,15.494,15.296000,13.812,16.501000,613.249,I,material_7,material_5,NaN
20772,47342,67.73,9.0,5.0,10.0,11.0,2.0,18.656,10.033195,18.242,...,11.134,16.519,15.525000,14.175,17.728000,783.349,I,material_7,material_5,NaN
20773,47343,126.15,9.0,5.0,8.0,16.0,11.0,16.536,11.226000,18.144,...,9.319,15.817,17.403000,16.437,15.179000,745.210,I,material_7,material_5,NaN
20774,47344,85.97,9.0,5.0,0.0,11.0,11.0,18.373,11.210000,17.030,...,13.726,14.605,17.460000,16.261,16.482000,647.980,I,material_7,material_5,NaN

In [45]:
all_data_X_imp[~all_data_X_imp['failure'].isnull()]

,id,loading,attribute_2,attribute_3,measurement_0,measurement_1,measurement_2,measurement_3,measurement_4,measurement_5,...,measurement_12,measurement_13,measurement_14,measurement_15,measurement_16,measurement_17,product_code,attribute_0,attribute_1,failure
0,0,80.10,9.0,5.0,7.0,8.0,4.0,18.040,12.518000,15.748,...,15.193,15.029,13.638146,13.034,14.684000,764.100,A,material_7,material_8,0.0
1,1,84.89,9.0,5.0,14.0,3.0,3.0,18.213,11.540000,17.717,...,11.755,14.732,15.425000,14.395,15.631000,682.057,A,material_7,material_8,0.0
2,2,82.43,9.0,5.0,12.0,1.0,5.0,18.057,11.652000,16.738,...,13.798,16.711,18.631000,14.094,17.946000,663.376,A,material_7,material_8,0.0
3,3,101.07,9.0,5.0,13.0,2.0,6.0,17.295,11.188000,18.576,...,10.020,15.250,15.562000,16.154,17.172000,826.282,A,material_7,material_8,0.0
4,4,188.06,9.0,5.0,9.0,2.0,8.0,19.346,12.950000,16.990,...,12.428,16.182,12.760000,13.153,16.412000,579.885,A,material_7,material_8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26565,26565,158.95,6.0,9.0,6.0,16.0,4.0,16.301,13.259000,18.068,...,10.112,15.795,18.572000,16.144,13.279117,729.131,E,material_7,material_6,0.0
26566,26566,146.02,6.0,9.0,10.0,12.0,8.0,17.543,10.036905,17.984,...,10.234,14.450,14.322000,13.146,16.471000,853.924,E,material_7,material_6,0.0
26567,26567,115.62,6.0,9.0,1.0,10.0,1.0,15.670,11.535000,16.778,...,8.668,15.069,16.599000,15.590,14.065000,750.364,E,material_7,material_6,0.0
26568,26568,106.38,6.0,9.0,2.0,9.0,4.0,18.059,10.031023,16.918,...,14.928,16.273,15.485000,13.624,12.865000,730.156,E,material_7,material_6,0.0
26569,26569,131.20,6.0,9.0,6.0,19.0,1.0,18.034,11.431000,16.918,...,11.006,15.875,13.366000,16.527,17.890000,602.354,E,material_7,material_6,0.0

In [46]:
all_train_new=all_data_X_imp[~all_data_X_imp['failure'].isnull()]
all_train_new.to_csv('data/train_imp.csv',index=False)

In [47]:
all_test_new=all_data_X_imp[all_data_X_imp['failure'].isnull()]
all_test_new.to_csv('data/test_imp.csv',index=False)